
from django.urls import path, include
from . import views

app_name = 'Hospital'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    # admin
    path('admindash', views.admindash, name='admindash'),
    path('accountant', views.accountant, name='accountant'),
    path('doctor', views.doctor, name='doctor'),
    path('bedallotment', views.bedallotment, name='bedallotment'),
    path('birthreport', views.birthreport, name='birthreport'),
    path('bloodbank', views.bloodbank, name='bloodbank'),
    path('blooddonor', views.blooddonor, name='blooddonor'),
    path('contactemails', views.contactemails, name='contactemails'),
    path('createpayroll', views.createpayroll, name='createpayroll'),
    path('deathreport', views.deathreport, name='deathreport'),
    path('department_facilities', views.department_facilities,
         name='departmentfacilities'),
    path('department', views.department, name='department'),
    path('frontend', views.frontend, name='frontend'),
    #path('login', views.login, name='login'),
    path('labaratorist', views.labaratorist, name='labaratorist'),
    path('manageprofile', views.manageprofile, name='manageprofile'),
    path('medicine', views.medicine, name='medicine'),
    path('noticeboard', views.noticeboard, name='noticeboard'),
    path('nurse', views.nurse, name='nurse'),
    path('operationreport', views.operationreport, name='operationreport'),
    path('patient', views.patient, name='patient'),
    path('paymenthistory', views.paymenthistory, name='paymenthistory'),
    path('payrolllist', views.payrolllist, name='payrolllist'),
    path('pharmacist', views.pharmacist, name='pharmacist'),
    path('receptionist', views.receptionist, name='receptionist'),
    path('systemsettings', views.systemsettings, name='systemsettings'),
    path('addpatientmodal', views.addpatientmodal, name='addpatientmodal'),
    path('adddoctormodal', views.adddoctormodal, name='adddoctormodal'),
    path('addaccountantmodal', views.addaccountantmodal, name='addaccountantmodal'),
    path('addnursemodal', views.addnursemodal, name='addnursemodal'),
    path('addreceptionistmodal', views.addreceptionistmodal,
         name='addreceptionistmodal'),
    path('addlabaratoristmodal', views.addlabaratoristmodal,
         name='addlabaratoristmodal'),
    path('addpharmacistmodal', views.addpharmacistmodal, name='addpharmacistmodal'),
    path('editpatientmodal/<int:pat_id>',views.editpatientmodal, name='editpatientmodal'),
    path('editpatientmodalD/<int:pat_id>',views.editpatientmodalD, name='editpatientmodalD'),
    path('adddepartmentmodal', views.adddepartmentmodal, name='adddepartmentmodal'),
    path('editdepartmentmodal/<int:dep_id>',
         views.editdepartmentmodal, name='editdepartmentmodal'),
    path('editreceptionistmodal/<int:id>',
         views.editreceptionistmodal, name='editreceptionistmodal'),
    path('editlabaratoristmodal/<int:id>',
         views.editlabaratoristmodal, name='editlabaratoristmodal'),
    path('editpharmacistmodal/<int:id>',
         views.editpharmacistmodal, name='editpharmacistmodal'),
    path('editaccountantmodal/<int:id>',
         views.editaccountantmodal, name='editaccountantmodal'),
        
    path('editdepartment', views.editdepartment, name='editdepartment'),
    path('deletedepartment/<int:id>',
         views.deletedepartment, name='deletedepartment'),
    path('deletedoctor/<int:id>', views.deletedoctor, name='deletedoctor'),
    path('deletenurse/<int:id>', views.deletenurse, name='deletenurse'),
    path('deletereceptionist/<int:id>', views.deletereceptionist, name='deletereceptionist'),
    path('deletepharmacist/<int:id>', views.deletepharmacist, name='deletepharmacist'),
    path('deletelabaratorist/<int:id>', views.deletelabaratorist, name='deletelabaratorist'),
    path('deleteaccountant/<int:id>', views.deleteaccountant, name='deleteaccountant'),
    
    path('deleteprescription/<int:id>', views.deleteprescription, name='deleteprescription'),
    path('deletepatient/<int:id>', views.deletepatient, name='deletepatient'),
    path('editdoctormodal/<int:doc_id>',
         views.editdoctormodal, name='editdoctormodal'),
    path('editdoctor', views.editdoctor, name='editdoctor'),
    path('editnursemodal/<int:nur_id>',
         views.editnursemodal, name='editnursemodal'),
    path('editnurse', views.editnurse, name='editnurse'),
    path('editpatient', views.editpatient, name='editpatient'),
    path('editpatientD', views.editpatientD, name='editpatientD'),
    
    path('editreceptionist', views.editreceptionist, name='editreceptionist'),
    path('editpharmacist', views.editpharmacist, name='editpharmacist'),
    path('editlabaratorist', views.editlabaratorist, name='editlabaratorist'),
    path('editaccountant', views.editaccountant, name='editaccountant'),
    path('markpaid/<int:id>', views.markpaid, name='markpaid'),
    path('markunpaid/<int:id>', views.markunpaid, name='markunpaid'),
    path('viewpayrolldetails/<int:id>', views.viewpayrolldetails, name='viewpayrolldetails'),
    path('editprescription', views.editprescription, name='editprescription'),
    path('editprescriptionmodal/<int:id>', views.editprescriptionmodal, name='editprescriptionmodal'),
    
    # doctor
    path('patientD', views.patientD, name='patientD'),
    path('doctordash', views.doctordash, name='doctordash'),
    path('appointmentD', views.appointmentD, name='appointmentD'),
    path('appointmentrequestD', views.appointmentrequestD,
         name='appointmentrequestD'),
    path('bedallotmentD', views.bedallotmentD, name='bedallotmentD'),
    path('bloodbankD', views.bloodbankD, name='bloodbankD'),
    path('medicationhistoryD', views.medicationhistoryD, name='medicationhistoryD'),
    path('payrolllistD', views.payrolllistD, name='payrolllistD'),
    path('pmnewD', views.pmnewD, name='pmnewD'),
    path('pmD', views.pmD, name='pmD'),
    path('pmDd/<int:id>', views.pmDd, name='pmDd'),
    path('prescriptionD', views.prescriptionD, name='prescriptionD'),
    path('profileD', views.profileD, name='profileD'),
    path('reportD', views.reportD, name='reportD'),
    path('approveappointment/<int:id>', views.approveappointment, name='approveappointment'),
    # doctorModals
    path('addappointmentD', views.addappointmentD, name='addappointmentD'),
    path('addbedallotmentD', views.addbedallotmentD, name='addbedallotmentD'),
    path('addpatientmodalD', views.addpatientmodalD, name='addpatientmodalD'),
    path('addprescriptionD', views.addprescriptionD, name='addprescriptionD'),
    path('addreportD', views.addreportD, name='addreportD'),
    path('viewdiagnosisreportD/<int:id>', views.viewdiagnosisreportD,
         name='viewdiagnosisreportD'),
     path('viewdiagnosisreportDD', views.viewdiagnosisreportDD,
         name='viewdiagnosisreportDD'),
    path('viewpayrolldetailsD', views.viewpayrolldetailsD,
         name='viewpayrolldetailsD'),
    path('viewprescriptionD/<int:id>', views.viewprescriptionD, name='viewprescriptionD'),
    path('viewprofileD/<int:patientID>',
         views.viewprofileD, name='viewprofileD'),
    path('viewreportfilesD', views.viewreportfilesD, name='viewreportfilesD'),
    path('editappointment', views.editappointment, name='editappointment'),
    path('editappointmentmodal/<int:id>',views.editappointmentmodal, name='editappointmentmodal'),
    path('deleteappointment/<int:id>', views.deleteappointment, name='deleteappointment'),
    # accountant
    path('accountdash', views.accountdash, name='accountdash'),
    path('invoicemanage', views.invoicemanage, name='invoicemanage'),
    path('invoice', views.invoice, name='invoice'),
    #path('payrolllistA', views.payrolllistA, name='payrolllistA'),
    path('profileA', views.profileA, name='profileA'),

    # labaratorist
    path('bloodbankL', views.bloodbankL, name='bloodbankL'),
    path('blooddonorL', views.blooddonorL, name='blooddonorL'),
    path('labdash', views.labdash, name='labdash'),
    path('addblooddonormodal', views.addblooddonormodal, name='addblooddonormodal'),
    path('payrollL', views.payrollL, name='payrollL'),
    path('profileL', views.profileL, name='profileL'),


    # nurse
    path('bed', views.bed, name='bed'),
    path('bedallotmentN', views.bedallotmentN, name='bedallotmentN'),
    path('blooddonorN', views.blooddonorN, name='blooddonorN'),
    path('bloodbankN', views.bloodbankN, name='bloodbankN'),
    path('patientN', views.patientN, name='patientN'),
    path('nursedash', views.nursedash, name='nursedash'),
    path('reportN', views.reportN, name='reportN'),
    path('payrollN', views.payrollN, name='payrollN'),
    path('profileN', views.profileN, name='profileN'),
    path('addpatientN', views.addpatientN, name='addpatientN'),
    path('addblooddonormodalN', views.addblooddonormodalN,
         name='addblooddonormodalN'),
    path('addreportmodalN', views.addreportmodalN, name='addreportmodalN'),
    path('addbedallotmentN', views.addbedallotmentN, name='addbedallotmentN'),
    path('addbed', views.addbed, name='addbed'),





    ###########patient
    path('prescriptionpatient', views.prescriptionpatient, name='prescriptionpatient'),
    path('appointmentpatient', views.appointmentpatient, name='appointmentpatient'),
    path('pendingappointment', views.pendingappointment, name='pendingappointment'),
    path('doctorpatient', views.doctorpatient, name='doctorpatient'),
    path('invoiceP', views.invoiceP, name='invoiceP'),
    path('messageP', views.messageP, name='messageP'),
    path('messagepD/<int:id>', views.messagepD, name='messagepD'),
    path('profileP', views.profileP, name='profileP'),
    path('applyappointment', views.applyappointment, name='applyappointment'),
    
    path('viewdocprofile/<int:id>', views.viewdocprofile, name='viewdocprofile'),
]
